name: Fluvius Short URL Generator

on:
  workflow_dispatch:
    inputs:
      contract_number:
        description: 'Data Access Contract Number'
        required: true
        type: string
      reference_number:
        description: 'Reference Number'
        required: true
        type: string
      flow:
        description: 'Flow (B2B or B2C)'
        required: true
        type: string
      dataPeriodFrom:
        description: 'How far back do you need the data (max 3 years back) (e.g., 2023-02-01T00:00:00Z)'
        required: false
        type: string

jobs:
  fluvius_short_url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          FLUVIUS_CLIENT_ID: ${{ secrets.FLUVIUS_CLIENT_ID }}
          FLUVIUS_TENANT_ID: ${{ secrets.FLUVIUS_TENANT_ID }}
          FLUVIUS_CERT_THUMBPRINT: ${{ secrets.FLUVIUS_CERT_THUMBPRINT }}
          OPINUM_CLIENT_SECRET: ${{ secrets.OPINUM_CLIENT_SECRET }}
          OPINUM_USERNAME: ${{ secrets.OPINUM_USERNAME }}
          OPINUM_PASSWORD: ${{ secrets.OPINUM_PASSWORD }}
        run: python fluvius_url.py ${{ github.event.inputs.contract_number }} ${{ github.event.inputs.reference_number }} ${{ github.event.inputs.flow }} ${{ github.event.inputs.dataPeriodFrom }}
